server:
 port : 8090

spring:
  application:
    name : volumen
  thymeleaf:
    cache : false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/volumendev1
    username : volumendev1
    password : password
    driver-class-name : org.postgresql.Driver
  sql:
    init:
      mode: always # to run schema.sql
  jpa : 
    show-sql: true
    hibernate :
      ddl-auto : update # create
    properties : 
      hibernate :
        dialect : org.hibernate.dialect.PostgreSQLDialect
#        generate_statistics : true
        enable_lazy_load_no_trans : true
  web : 
    resources :
      static-locations : classpath:/resources,file:./uploads
# max file size
  servlet:
    multipart:
      max-file-size : 10MB
# max request size
      max-request-size: 10MB
      enabled: true
hibernate : 
  connection : 
    autocommit : false

storage:
  location: ./uploads
